apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default                  # ← ده الحقل اللي كان ناقص – أضفه هنا
  source:
    repoURL: https://github.com/MaiSalama/CloudDevOpsProject.git
    targetRevision: deploy-branch   # تأكد إنه الـ branch الصحيح
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: app-namespace
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true