apiVersion: v1
kind: Service
metadata:
  name: my-app-metrics
  namespace: app-namespace
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000
