@Library('ci-lib') _

pipeline {
    agent any
    
    environment {
        APP_DIR    = 'src'
        IMAGE_NAME = 'imaisalama/devops-app'
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

 stages {

    stage('BuildImage') {
      steps {
        docker_build(APP_DIR, IMAGE_NAME, IMAGE_TAG)
      }
    }

    // stage('ScanImage') {
    //   steps {
    //     scanImage(IMAGE_NAME, IMAGE_TAG)
    //   }
    // }

    // stage('PushImage') {
    //   steps {
    //     pushImage(IMAGE_NAME, IMAGE_TAG)
    //   }
    // }

    // stage('RemoveImageLocally') {
    //   steps {
    //     removeImageLocally(IMAGE_NAME, IMAGE_TAG)
    //   }
    // }

    // stage('DeployOnK8s') {
    //   steps {
    //     deployOnK8s(APP_DIR)
    //   }
    // }
  }
}
    

 

  post {

    success {
      echo 'CI/CD pipeline completed successfully'
    }

    failure {
      echo 'Pipeline failed'
    }

  }